# Generated by Django 4.2.0 on 2025-07-30 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('read_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='阅读时间')),
                ('session_key', models.CharField(max_length=40, verbose_name='会话键')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading_statistics.article', verbose_name='文章')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '阅读记录',
                'verbose_name_plural': '阅读记录',
                'db_table': 'reading_records',
                'ordering': ['-read_time'],
            },
        ),
    ]