# Generated by Django 4.2.0 on 2025-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_statistics', '0002_add_reading_record'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='readingrecord',
            index=models.Index(fields=['article', 'user'], name='reading_rec_article_user_idx'),
        ),
        migrations.AddIndex(
            model_name='readingrecord',
            index=models.Index(fields=['article', 'ip_address'], name='reading_rec_article_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='readingrecord',
            index=models.Index(fields=['read_time'], name='reading_rec_read_time_idx'),
        ),
    ]