# Generated by Django 4.2.0 on 2025-07-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading_statistics', '0003_add_reading_record_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='总阅读次数')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='独立访客数')),
                ('registered_user_views', models.PositiveIntegerField(default=0, verbose_name='注册用户阅读次数')),
                ('anonymous_views', models.PositiveIntegerField(default=0, verbose_name='匿名用户阅读次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reading_statistics.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章统计',
                'verbose_name_plural': '文章统计',
                'db_table': 'article_statistics',
            },
        ),
    ]