# Generated by Django 4.2.0 on 2025-07-31 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading_statistics', '0004_add_article_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='阅读次数')),
                ('first_read_time', models.DateTimeField(verbose_name='首次阅读时间')),
                ('last_read_time', models.DateTimeField(verbose_name='最后阅读时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading_statistics.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户阅读统计',
                'verbose_name_plural': '用户阅读统计',
                'db_table': 'user_reading_statistics',
            },
        ),
        migrations.AddConstraint(
            model_name='userreadingstatistics',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article'),
        ),
    ]