# Generated by Django 4.2.0 on 2025-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_statistics', '0005_add_user_reading_statistics'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userreadingstatistics',
            index=models.Index(fields=['user'], name='user_stats_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userreadingstatistics',
            index=models.Index(fields=['article'], name='user_stats_article_idx'),
        ),
    ]