# Generated by Django 4.2.0 on 2025-07-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_statistics', '0006_add_user_statistics_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheHitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('cache_type', models.CharField(max_length=50, verbose_name='缓存类型')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='总请求数')),
                ('cache_hits', models.PositiveIntegerField(default=0, verbose_name='缓存命中数')),
                ('cache_misses', models.PositiveIntegerField(default=0, verbose_name='缓存未命中数')),
                ('hit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='命中率')),
            ],
            options={
                'verbose_name': '缓存命中率统计',
                'verbose_name_plural': '缓存命中率统计',
                'db_table': 'cache_hit_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='cachehitstatistics',
            constraint=models.UniqueConstraint(fields=('date', 'cache_type'), name='unique_date_cache_type'),
        ),
    ]